version: "3.8"

services:
  flask_app:
    build: .
    container_name: flask_auth_api
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "5000:5000"
    networks:
      - app_network
    volumes:
      - .:/app


  db:
    image: postgres:15
    container_name: flask_auth_db
    restart: always
    environment:
      POSTGRES_DB: flask_auth_db
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    networks:
      - app_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flask_user -d flask_auth_db"]
      interval: 10s
      timeout: 5s

  redis:
    image: redis:latest
    container_name: flask_auth_redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
